AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  lambda-s3 upload

  
# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3

Resources:
  LambdaS3Upload:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: upload/
      Handler: upload.lambdaHandler
      Runtime: nodejs10.x
      Events:
        LambdaS3Upload:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /upload
            Method: post

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  LambdaS3UploadApi:
    Description: "API Gateway endpoint URL for Prod stage for Lambda S3 Upload function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/prod/s3-upload/"
  LambdaS3Upload:
    Description: "Lambda S3 Upload Function ARN"
    Value: !GetAtt LambdaS3Upload.Arn
  LambdaS3UploadIamRole:
    Description: "Implicit IAM Role created for Lambda S3 Upload function"
    Value: !GetAtt LambdaS3UploadFunctionRole.Arn
